# Generated by Django 3.1.3 on 2021-11-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('merchantID', models.CharField(max_length=50)),
                ('pending_time', models.FloatField(default=1636359640.7160208)),
                ('cellNUM', models.CharField(max_length=15)),
                ('bank', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=674147),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1636359940.6306145),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=258645105845452490507676407650788874158),
        ),
        migrations.AlterField(
            model_name='factor',
            name='off_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstaPay.offcode'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1636360540.6888964),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1636359640.6891305),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='258645105766224327993412070057244923822', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=4241445824997139.0),
        ),
        migrations.CreateModel(
            name='SamanPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalID', models.CharField(max_length=50)),
                ('pendingID', models.CharField(max_length=25)),
                ('multiplex_shaba', models.CharField(max_length=50)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.pending')),
            ],
        ),
        migrations.CreateModel(
            name='SadadPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalID', models.CharField(max_length=50)),
                ('pendingID', models.CharField(max_length=50)),
                ('signData', models.CharField(max_length=50)),
                ('multiplex_shaba', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('resCode', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.pending')),
            ],
        ),
        migrations.AddField(
            model_name='pending',
            name='factor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.factor'),
        ),
    ]
