# Generated by Django 3.1.3 on 2021-10-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0002_auto_20211018_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=821279),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1634544642.979532),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=65253388440863433014683428973356246485),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1634545243.4127164),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1634544343.4127433),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='65253388361635270500419091379812296149', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=1634544343.3582697),
        ),
    ]
