# Generated by Django 3.1.3 on 2021-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0002_auto_20211122_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=222442),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1637596436.439573),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=238614854529693028909935654526963905197, max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factor',
            name='create_time',
            field=models.FloatField(default=1637596136.5389662),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=238614854688149353938464329714051805869),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1637597036.5296862),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1637596136.5298758),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='238614854608921191424199992120507855533', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.FloatField(default=1637596136.5889068),
        ),
        migrations.AlterField(
            model_name='pending',
            name='pending_time',
            field=models.FloatField(default=1637596136.5565996),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=4244650823367339.5),
        ),
        migrations.AlterField(
            model_name='samanpayment',
            name='payment_time',
            field=models.FloatField(default=1637596136.5970979),
        ),
    ]
