# Generated by Django 3.1.3 on 2021-11-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0002_auto_20211108_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('payment_time', models.FloatField(default=1636797802.1449964)),
                ('amount', models.IntegerField()),
                ('traceNO', models.CharField(max_length=50)),
                ('paymentID', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=688687),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1636798100.576606),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=317832819981053575015014625027346126023),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1636798702.055918),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1636797802.056197),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='317832819901825412500750287433802175687', max_length=50),
        ),
        migrations.AlterField(
            model_name='pending',
            name='pending_time',
            field=models.FloatField(default=1636797802.0891242),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=4242581537035149.5),
        ),
        migrations.CreateModel(
            name='SamanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNUM', models.CharField(max_length=50)),
                ('payment_time', models.FloatField(default=1636797802.1582747)),
                ('terminalID', models.CharField(max_length=50)),
                ('Verify_Status', models.BooleanField(default=False)),
                ('PaymentID', models.CharField(max_length=50)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.payment')),
                ('saman_pending', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.samanpending')),
            ],
        ),
        migrations.CreateModel(
            name='SadadPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentID', models.CharField(max_length=50)),
                ('Hashed_Card', models.CharField(max_length=50)),
                ('primary_acc_no', models.CharField(max_length=50)),
                ('switch_res_Code', models.CharField(max_length=50)),
                ('rescode', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('retrival_ref_no', models.CharField(max_length=50)),
                ('system_trace_no', models.CharField(max_length=50)),
                ('verify_status', models.BooleanField(default=False)),
                ('payment_time', models.FloatField(default=1636797802.1691823)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.payment')),
                ('sadad_pending', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.sadadpending')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='factor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.factor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='InstaPay.pending'),
        ),
    ]
