# Generated by Django 3.1.3 on 2021-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0003_auto_20211113_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='bloger_payment_serial',
        ),
        migrations.AddField(
            model_name='factor',
            name='create_time',
            field=models.FloatField(default=1636790506.5991664),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=564050),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1636790806.3917472),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer_payment_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer_payment_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer_payment_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer_payment_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer_payment_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=322574869688708612843743526536417367239),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1636791406.5964756),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1636790506.5965028),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='322574869609480450329479188942873416903', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.FloatField(default=1636790506.610046),
        ),
        migrations.AlterField(
            model_name='pending',
            name='pending_time',
            field=models.FloatField(default=1636790506.6038208),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=4242562629844684.5),
        ),
        migrations.AlterField(
            model_name='sadadpayment',
            name='payment_time',
            field=models.FloatField(default=1636790506.6159832),
        ),
        migrations.AlterField(
            model_name='samanpayment',
            name='payment_time',
            field=models.FloatField(default=1636790506.612378),
        ),
    ]
