# Generated by Django 3.1.3 on 2021-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0003_auto_20211018_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='verify_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=762342),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1634634405.4068468),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=63063288781511390226948143210950568302),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1634635005.4684467),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1634634105.4686482),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='63063288702283227712683805617406617966', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=1634634105.4543672),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_hashcode',
            field=models.CharField(default='32', max_length=128),
        ),
    ]
