# Generated by Django 3.1.3 on 2021-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaPay', '0005_auto_20211023_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code',
            field=models.IntegerField(default=944590),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='forgot_password_code_deadline',
            field=models.FloatField(default=1635151687.3823826),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_id',
            field=models.IntegerField(default=196095064005239369316395418024990980611),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='deadline',
            field=models.FloatField(default=1635152287.4355505),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='generating_time',
            field=models.FloatField(default=1635151387.435575),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='off_code_id',
            field=models.CharField(default='196095063926011206802131080431447030275', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='InstaPay/Product_Image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_code_deadline',
            field=models.FloatField(default=1635151387.428637),
        ),
    ]
